apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - order-depl.yaml
  - orders-mongo-depl.yaml

images:
  - name: ghcr.io/beltawn3507/orders
    newTag: e5cc4f334c7098164adfc2360852a43100db05db

