apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - order-depl.yaml
  - orders-mongo-depl.yaml

images:
  - name: ghcr.io/beltawn3507/orders
    newTag: 10760c4514d75c2fff7e7056248cb02d7afd7b24

