apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - expiration-depl.yaml
  - expiration-redis-depl.yaml

images:
  - name: ghcr.io/beltawn3507/expiration
    newTag: 2d51cf6f2428e1779eff442f95c0e7e6f45d7587

