apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - payments-depl.yaml
  - payments-mongo-depl.yaml

images:
  - name: ghcr.io/beltawn3507/payments
    newTag: 18807aa1ba2f505dfcd8e8834741227d33a4d803

