apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-depl.yaml
  - auth-mongo-depl.yaml

images:
  - name: ghcr.io/beltawn3507/auth
    newTag: b6608ea695cf22bf93b9da87579bd5ae05783dd6

